version: '3.9'

services:
  frontend:
    build: .
    container_name: money-frontend
    ports:
      - "3000:80"
    env_file:
      - .env.local

networks:
  default:
    name: money-frontend-network
